### REGISTER

POST http://localhost:5000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "username" : "toto",
  "email" : "toto@mail.fr",
  "password" : "toto"
}       

### LOGIN

POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "titi",
  "password": "titi"
}