### CREATE
POST http://localhost:5000/api/orders/new HTTP/1.1
Content-Type: application/json
token : e eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTRkYzk1MDc5NzIzZjAzOGExNmY1YSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0MTU3MDEyNiwiZXhwIjoxNjQxODI5MzI2fQ.6G7iZLv7sErvn5Ce5d8-4bKGGaFMSPt6mLsqSW6VzGE

{
  "userId": "619bcb60cc19631070635be9",
  "products": [
    {
      "productId" : "61be65c42974aea7e9b60a5d",
      "quantity" : 10
    }
],
"amount" : 10000,
"address" : "18 rue de la republique-31300-Toulouse"
}

### UPDATE
PUT http://localhost:5000/api/orders/61b2041f4435c98c45dde442 HTTP/1.1
token: e eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTRkYzk1MDc5NzIzZjAzOGExNmY1YSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0MTU3MDEyNiwiZXhwIjoxNjQxODI5MzI2fQ.6G7iZLv7sErvn5Ce5d8-4bKGGaFMSPt6mLsqSW6VzGE
Content-Type: application/json

{
"products":[
   {
      "productId" : "61be65c42974aea7e9b60a5d", "quantity": "2"
    }],
    "amount" : 6000,
    "address" : "18 rue de la republique-31300-Toulouse"
}
### DELETE
DELETE http://localhost:5000/api/orders/61b2341bf6068563a012704d HTTP/1.1
token: e eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTRkYzk1MDc5NzIzZjAzOGExNmY1YSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0MTU3MDEyNiwiZXhwIjoxNjQxODI5MzI2fQ.6G7iZLv7sErvn5Ce5d8-4bKGGaFMSPt6mLsqSW6VzGE

### GET USER ORDERS
GET http://localhost:5000/api/orders/619bcb60cc19631070635be9
token: e eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTRkYzk1MDc5NzIzZjAzOGExNmY1YSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0MTU3MDEyNiwiZXhwIjoxNjQxODI5MzI2fQ.6G7iZLv7sErvn5Ce5d8-4bKGGaFMSPt6mLsqSW6VzGE

### GET ALL ORDERS
GET http://localhost:5000/api/orders/ HTTP/1.1
token: e eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTRkYzk1MDc5NzIzZjAzOGExNmY1YSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0MTU3MDEyNiwiZXhwIjoxNjQxODI5MzI2fQ.6G7iZLv7sErvn5Ce5d8-4bKGGaFMSPt6mLsqSW6VzGE

### GET INCOME
GET http://localhost:5000/api/orders/income HTTP/1.1
token: e eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTRkYzk1MDc5NzIzZjAzOGExNmY1YSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0MTMxMDc1NSwiZXhwIjoxNjQxNTY5OTU1fQ.IJd0uDt6s7zzlMmBNzoN6W-iFYripf7zvxGbLz3b6ZI